import XCTest
@testable import AIMenu

final class WebRemoteAuthServiceTests: XCTestCase {

    func testValidateCorrectToken() async {
        let service = WebRemoteAuthService(initialToken: "test-token-123")
        let result = await service.validate(candidateToken: "test-token-123", remoteAddress: "127.0.0.1")
        XCTAssertTrue(result)
    }

    func testValidateWrongToken() async {
        let service = WebRemoteAuthService(initialToken: "correct")
        let result = await service.validate(candidateToken: "wrong", remoteAddress: "127.0.0.1")
        XCTAssertFalse(result)
    }

    func testCurrentToken() async {
        let service = WebRemoteAuthService(initialToken: "my-token")
        let token = await service.currentToken()
        XCTAssertEqual(token, "my-token")
    }

    func testRegenerateTokenChangesValue() async {
        let service = WebRemoteAuthService(initialToken: "old-token")
        let newToken = await service.regenerateToken()
        XCTAssertNotEqual(newToken, "old-token")
        XCTAssertTrue(newToken.hasPrefix("web-"))
        let currentToken = await service.currentToken()
        XCTAssertEqual(currentToken, newToken)
    }

    func testAutoGeneratedTokenFormat() async {
        let service = WebRemoteAuthService()
        let token = await service.currentToken()
        XCTAssertTrue(token.hasPrefix("web-"))
        XCTAssertGreaterThan(token.count, 10)
    }

    func testIPBanAfterMaxAttempts() async {
        let service = WebRemoteAuthService(initialToken: "correct")
        let ip = "192.168.1.100"

        // 5 failed attempts should trigger ban
        for _ in 0..<5 {
            _ = await service.validate(candidateToken: "wrong", remoteAddress: ip)
        }

        // Even correct token should fail when banned
        let result = await service.validate(candidateToken: "correct", remoteAddress: ip)
        XCTAssertFalse(result)
    }

    func testNoBanBeforeMaxAttempts() async {
        let service = WebRemoteAuthService(initialToken: "correct")
        let ip = "10.0.0.1"

        // 4 failures (below threshold of 5)
        for _ in 0..<4 {
            _ = await service.validate(candidateToken: "wrong", remoteAddress: ip)
        }

        // Correct token should still work
        let result = await service.validate(candidateToken: "correct", remoteAddress: ip)
        XCTAssertTrue(result)
    }

    func testResetBansClearsAll() async {
        let service = WebRemoteAuthService(initialToken: "correct")
        let ip = "10.0.0.2"

        for _ in 0..<5 {
            _ = await service.validate(candidateToken: "wrong", remoteAddress: ip)
        }
        let bannedBefore = await service.isIPBanned(ip)
        XCTAssertTrue(bannedBefore)

        await service.resetBans()
        let bannedAfter = await service.isIPBanned(ip)
        XCTAssertFalse(bannedAfter)

        let result = await service.validate(candidateToken: "correct", remoteAddress: ip)
        XCTAssertTrue(result)
    }

    func testDifferentIPsAreSeparate() async {
        let service = WebRemoteAuthService(initialToken: "correct")

        // Ban ip1
        for _ in 0..<5 {
            _ = await service.validate(candidateToken: "wrong", remoteAddress: "1.1.1.1")
        }

        // ip2 should not be affected
        let result = await service.validate(candidateToken: "correct", remoteAddress: "2.2.2.2")
        XCTAssertTrue(result)
    }

    func testSuccessfulAuthClearsFailedCount() async {
        let service = WebRemoteAuthService(initialToken: "correct")
        let ip = "10.0.0.3"

        // 3 failures
        for _ in 0..<3 {
            _ = await service.validate(candidateToken: "wrong", remoteAddress: ip)
        }

        // Successful auth should reset
        _ = await service.validate(candidateToken: "correct", remoteAddress: ip)

        // 3 more failures should not trigger ban (counter was reset)
        for _ in 0..<3 {
            _ = await service.validate(candidateToken: "wrong", remoteAddress: ip)
        }
        let stillBanned = await service.isIPBanned(ip)
        XCTAssertFalse(stillBanned)
    }

    func testBanUsesNormalizedAddressInsteadOfConnectionPort() async {
        let service = WebRemoteAuthService(initialToken: "correct")

        for index in 0..<5 {
            _ = await service.validate(
                candidateToken: "wrong",
                remoteAddress: "127.0.0.1:\(5000 + index)"
            )
        }

        let banned = await service.isIPBanned("127.0.0.1:9999")
        XCTAssertTrue(banned)

        let result = await service.validate(candidateToken: "correct", remoteAddress: "127.0.0.1:10000")
        XCTAssertFalse(result)
    }
}
